### ISSUE TITLE
File-Uploading Issue

### ISSUE THREAD

**Issue by vyvanand** [kostysh/File-uploading-component-for-Sencha-Touch#10]
I can able to upload file only once in IOS. If I tried to upload for second time, I cannot able to upload.. What will be the reason??

**Comment by kostysh** [comment]
Please check javascript console. Does you got any errors?

**Comment by vyvanand** [comment]
No errors are found in javascript. The same thing is working in chrome browser of pc.I can able to upload many pictures at many times.

**Comment by kostysh** [comment]
I cannot reproduce this issue. Just tried doing upload files multiple times and with success

**Comment by jstxx** [comment]
So I found this issue too- perhaps it only occurs when using a navigation view?  It will work multiple times if you stay on the page but only seems to occur after navigating away from the current view.

**Comment by kostysh** [comment]
"navigation view" is a specific component. By default, each time then you make .pop() in this component, this component will destroy a previous pushed view.
You can try to configure autoDestroy property for Navigation view - to false.

**Comment by vyvanand** [comment]
Thanks All. I fixed this issue
