### ISSUE TITLE
iPad 2 with OS 6.0 - File Upload does't open any dialog/picker

### ISSUE THREAD

**Issue by jonswaino** [kostysh/File-uploading-component-for-Sencha-Touch#11]
Really like the component.  I've tried the file uploader component in the Chrome desktop browser, and a dialog correctly shows up to be able to select the file to upload.  However, on my iPad 2 running iOS6, no dialog/picker shows at all.

I've heard that previously in iOS mobile versions of Safari did not support this feature, but iOS6 would fix this issue.  So I don't know what the problem is.  Have you any idea what might be causing this?

**Comment by kostysh** [comment]
sorry, but I can not test this issue, because I have no iPad 2. But I know what other users uses fileup component on iPad 2 without any problems.
