### ISSUE TITLE
File Uploader fails on anything but a Http 200 response

### ISSUE THREAD

**Issue by jonswaino** [kostysh/File-uploading-component-for-Sencha-Touch#12]
I have a ASP.NET WebAPI controller which returns a HTTP Created (201) which is treated as a failure by the component. Shouldn't it view a 201 as a success? It might be worth treating all Http 200+ codes as success rather than failures. What do you think?

**Comment by kostysh** [comment]
I think - HTTP Created (201) - not a standard response for most cases. For your case you can change line: 438

**Comment by jonswaino** [comment]
Ok thanks, I'll leave it to you to decide whether you want to change your code or not. I'll still make my change on my own local copy.

**Comment by kostysh** [comment]
Just updated component repository. New feature for you: configurable
success response codes
Now you can configure your default codes by
setDefaultSuccessCodes([200,201])
I think this is will be universal solution for all cases.

K.

**Comment by talhakabakus** [comment]
Thanks for this useful extension, appreciated a lot. I've been facing same issue, just found solution after dig inside your code. At line 455, HTTP response code control should be changed like this to properly search response code inside default success codes: 
`if(Ext.Array.indexOf(me.getDefaultSuccessCodes(), parseInt(this.status)) != -1)`

**Comment by kostysh** [comment]
Thank you for advice! Not noticed this simple issue
Just fixed.
Thanks!
