### ISSUE TITLE
Server Java

### ISSUE THREAD

**Issue by Nertil** [kostysh/File-uploading-component-for-Sencha-Touch#17]
Hi kostysh,

This extention is powerfull, especially for those who like me are new in sencha touch.

My problem is that i have a java server side, so I was looking for a servlet java (or something that runs under tomca) that proccess the post request of the client. I tryed to implement it by myself but i failed (in the HttpServletRequest that comes in the servlet there are no "Parts")

Can you help me
Thanks

**Comment by kostysh** [comment]
Sorry, but I never used java. So can not help you.
I think you should ask on Sencha forum, maybe someone can help you

**Comment by Nertil** [comment]
Thanks for the quick response anyway.

2013/7/17 Constantine Smirnov notifications@github.com
