### ISSUE TITLE
Extjs 6.0 modern application

### ISSUE THREAD

**Issue by rahulyadav-walkingtree** [kostysh/File-uploading-component-for-Sencha-Touch#26]
I am unable to integrate with Extjs6.0 modern application,when i click on button(Browse) then popup window is not render but 'onButtonTap()' function is called properly.Any help

**Comment by kostysh** [comment]
The "file uploading component" was developed for old version of Sencha Touch and may not work in latest versions of ExtJS. Unfortunately I am not going to support this component anymore.

**Comment by rahulyadav-walkingtree** [comment]
Thanks kostysh.
