### ISSUE TITLE
Browser Site-Reload after choosing a File

### ISSUE THREAD

**Issue by StefanNeuser** [kostysh/File-uploading-component-for-Sencha-Touch#5]
Hi, first a wanna say is: Thank u alot for your Extension, nice work!

I'm testing my ST2 Webapp on a Android 4.1 Device with Chrome and Core Browser. When i will upload a Imagefile the Browser reloads the complete app with similar browser refresh.

Could it be, that your Extension only works fine when i use it within a native app?

**Comment by kostysh** [comment]
Hi,
yes I confirm this issue. On my 4.0.3 Android smartphone I got same problem, even on Chrome Mobile (not core browser only). But I think -  this is issue of Android OS (bug).
You can try to do one small experiment:
Please create a simple HTML page with just one form and one input (type=file) element and without any javasctipt, just HTML.
Open this page in core Android browser or in Google Chrome for mobile. Try to choose a file from camera or from phone gallery, ot take a video.
In the minimum of 90% cases - browser will reload the page :(((
Point your attantion - no javascript, only HTML.

BUT, on some devices this page refresh not occurs, even on my smartphone 1 from 10 cases have a success. Weird...

By the way, here I found same ticket: https://github.com/valums/file-uploader/issues/489

**Comment by kostysh** [comment]
I registered this issue on Android bug-tracker. If you can, please leave your comments there: https://code.google.com/p/android/issues/detail?id=53088

**Comment by shaikhaezaz80** [comment]
I too have this issues on my android phone.
