### ISSUE TITLE
Choose another type of file

### ISSUE THREAD

**Issue by andersonef** [kostysh/File-uploading-component-for-Sencha-Touch#6]
In first place, congratulations for this component, I like it very much, very simple to use.
Well, I tested it on my android and it works well for images and videos, but my project needs the user upload a JSON file. 
Can you help me? 
Thanks.

**Comment by kostysh** [comment]
Why not? JSON file is a kind of TXT file.
Or you want load file locally and use it as object?
It is possible. You should override (or rewrite) "doLoad" method. Inside this method you should use "readAsText" instead of "readAsDataURL" and then Ext.decode(yourFileTextContent)

**Comment by andersonef** [comment]
I'm developing an application to tablet. The box of choosing file works well in the browser, but on tablet, look how it looks.
![Screenshot_2013-03-15-13-35-31 1 ](https://f.cloud.github.com/assets/3864077/263634/72fb0a5a-8d75-11e2-8016-eaae6317dce0.png)

**Comment by kostysh** [comment]
this situation depends on device (some vendors allow and some not). On some devices you can choose file from file system.

**Comment by andersonef** [comment]
Understand... 
Do you know if there's a way, some param I can send to phonegap that I can choose another type of file?

**Comment by kostysh** [comment]
Phonegap has own API to filesystem
http://docs.phonegap.com/en/2.5.0/cordova_file_file.md.html#File
You can use this API instead of FileReader

**Comment by andersonef** [comment]
I think I'll need use this instead your component =(
But thank you very much for your help. Congratulations for your great job ^^

**Comment by kostysh** [comment]
not instead of my component - you can modify the component. 
Fileup.js - line 384
you should use here Phonegap API instead of FileReader (HTML5 API)

**Comment by andersonef** [comment]
Understand... I'll try here.. Thanks ^^
