### ISSUE TITLE
select a photo from a camer  in ios , it will rotate 90 revolutions.

### ISSUE THREAD

**Issue by xueyu-bingley** [kostysh/File-uploading-component-for-Sencha-Touch#9]
I have try your online demo ,it's same

**Comment by kostysh** [comment]
my component not handle EXIF information and image is shown as-is. You can write image into canvas and rotate it as you want.

**Comment by xueyu-bingley** [comment]
OK I got it . thanks very much .

**Comment by xueyu-bingley** [comment]
Hi ,  kostysh 
   I want use your component  in our web app based on secha touch 2.2  to upload photo to my web service  .
Is it available to do that ?   If yes , how can I do that ? thanks in advance .

**Comment by kostysh** [comment]
Hi, if your question is about license - you can freely use this component in conformity with GNU GPL v.3
If you asked about component usage with ST 2.2 - not tested yet, but I think component should work.
